### ISSUE TITLE
ESM Compatibility

### ISSUE THREAD

**Issue by camperdave** [linonetwo/langchain-alpaca#5]
I've been trying to use this module in my ESM / nodeJS project, and unfortunately `require.resolve` (as used in constants.ts defaultBinaryPath) is not available outside of a CJS context.

I've created a fork to try and experiment around this, and I'll update this issue if I can get it working in both CJS/ESM!

**Comment by linonetwo** [comment]
Thanks! I had trouble locating dist/binary folder inside the code, so GPT let me use that. It would be awesome if you can come up with a better idea!

**Comment by camperdave** [comment]
@linonetwo 

Sorry that it took me a few days to circle back around to this, but I believe that I've managed to make it compatible with both CJS and ESM using some existing functionality of the `tsup` tool you've already selected to build this project.

https://github.com/linonetwo/langchain-alpaca/pull/7

Since I'm pretty new to langchain still, please let me know if this breaks something I haven't managed to test on my local machine!

**Comment by linonetwo** [comment]
Thanks, please try v0.3.2 . On local you can run `pnpm runExample`, don't forget to `ln -s` the model to here
![截屏2023-03-26 00 26 07](https://user-images.githubusercontent.com/3746270/227729601-986cdcda-2b0e-4642-88eb-6783f3da0c60.png)
